name: Test

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        bash-version: ["3.0", 3.1, 3.2, "4.0", 4.1, 4.2, 4.3, 4.4, "5.0", 5.1]

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Bash ${{ matrix.bash-version }}
        run: |
          git clone https://github.com/ueokande/bashvm $HOME/.bashvm
          source $HOME/.bashvm/bin/bashvm-init
          bashvm use --install ${{ matrix.bash-version }}
          bash --version | head -1
          echo ${BASH_VERSION}
      - name: Setup Bats
        run: |
          sudo apt install bats
      - name: Install funnychar
        run: |
          sudo install -m 0755 funnychar /usr/local/bin/funnychar
      - name: Run tests
        run: |
          chmod +x test.bats && ./test.bats
